export const ALL_PRODUCT_REQUEST = 'ALL_PRODUCT_REQUEST'
export const ALL_PRODUCT_SUCCESS = 'ALL_PRODUCT_SUCCESS'
export const ALL_PRODUCT_FAIL = 'ALL_PRODUCT_FAIL'
export const ADD_CART_SUCCESS = 'ADD_CART_SUCCESS'
export const CLEAR_ERRORS = 'CLEAR_ERRORS'
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART';
